sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: OhJMpjlVqy3a6vRjw3+bkhHkbktDS5LYMLuZROt8+cENB2WIoZVzN1y1jXDS7ix4DKyxNJFZJ07Mq49KznbSzTFShOatape1DW+jkDJJoW31cH3puk64v2xCR8QCILnKgDya3t1jnPMnEO5/bWU0JYWzKx7trso8oam5KcEVR+Wa+ICy3FLNbsnaeuu/Ab9gmP1pRnU/tUwIN+BeKEHY3mqj0P216JIGw3C5Jyoum0F6ucMqhK1B2I1v/c6nuyJZLpt0A+L72CiVLzT5TNZYmmlQt/bLHTMECXcryENGg/kkqbNCMeWyKtch7e+Wv7T+p9VGQqXOXfzOpxdfpN3G/OXIdFqa1TdnlU/n06bmS+LTaWpA/EWWBoTZW/rPas/v/xQ8yckOxnzVNmuOjb80rvE3XP3KSoPBUKZsy6s8Thqwzja+wKZOJxKOLtxnq4xdzt4vrJKyq6vQos01UkeIxKKDSeawClYal0XYR5x0BnQMsIHRT0cvq5xkg8S0PKUkBbLi0dXxHIzr7EPzc47I+AxDsqBLHAXOQdaxRCf1SWluu43SpoHLmaHAfv5aZXcsGOYNwq30k52cQiTN9lkuIASdsC8+AgkWn7HvcDtdvmUlLDsxtrNR43juEm7c5rvaip5xCCGu9LU6L9ESfeYipTFY9onmeZaKoMmsteuWEfc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Haydn_3788
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy